apiVersion: k3d.io/v1alpha3
kind: Simple 
name: mycluster
servers: 1
agents: 3
image: rancher/k3s:v1.23.2-rc1-k3s1
kubeAPI:
 hostIP: "127.0.0.1"
 hostPort: "6445"
ports:
 - port: 8080:80
   nodeFilters:
    - loadbalancer
options:
 k3d:
   wait: true
   timeout: "60s"
 k3s:
   extraArgs:
      - arg: --tls-san=my.host.domain
        nodeFilters:
          - server:*
 kubeconfig:
   updateDefaultKubeconfig: true
   switchCurrentContext: true