apiVersion: k3d.io/v1alpha4
kind: Simple 
metadata:
  name: mycluster
servers: 1
agents: 3
image: rancher/k3s:v1.26.3-k3s1
kubeAPI:
 hostIP: "127.0.0.1"
 hostPort: "6445"
ports:
 - port: 9090:80
   nodeFilters:
    - loadbalancer
options:
 k3d:
   wait: true
   timeout: "60s"
 k3s:
   extraArgs:
      - arg: --tls-san=my.host.domain
        nodeFilters:
          - server:*
      - arg: '--kube-apiserver-arg=feature-gates=PDBUnhealthyPodEvictionPolicy=true'
        nodeFilters:
          - server:*
 kubeconfig:
   updateDefaultKubeconfig: true
   switchCurrentContext: true
